import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import NavigasiHomePage from "@/components/navigasiHomepage";
import Footer from "@/components/footer";
import Image from "next/image";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex justify-center">

      <div
        className={`${geistSans.variable} ${geistMono.variable} antialiased   w-[1280px] h-[100vh] relative`}
        >
          <div className="absolute top-0 left-0 z-0">
        <Image
      src='/sampleimage.jpg'
      alt=""
      width= {1280}
      height={500}
      className="mb-10"
      />
        </div>
          <div className=" mt-10 mb-5 z-10">

        <NavigasiHomePage/>
        
          </div>
          <div className="relative z-1 mt-[600px]">

        {children}
      <Footer/>
          </div>
      </div>
          </body>
          
    </html>
  );
}
